# version: "3"

# services:
#   web:
#     build: .
#     command: sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
#     ports:
#       - 8000:8000


version: "3.8"

services:
  web:
    build: .
    command: sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    ports:
      - "8000:8000"
    volumes:
      - ./credentials:/app/credentials:ro  
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/GOOGLE_APPLICATION_CREDENTIALS.json  
