# ---
# - name: Run Python code in Docker container and retrieve data
#   hosts: localhost
#   gather_facts: no
#   tasks:
#     - name: Clone repository
#       git:
#         repo: 'https://github.com/fentresspaul61B/Jellyfish-Videos.git'
#         dest: './yourrepository'
#         clone: yes
#         update: yes

#     - name: Build Docker image
#       community.docker.docker_image:
#         build:
#           path: "./yourrepository"
#         name: "your_image"
#         tag: "latest"
#         source: build

#     - name: Run Docker container
#       community.docker.docker_container:
#         name: "your_container"
#         image: "your_image:latest"
#         command: "python your_script.py"
#         volumes:
#           - "./yourrepository:/app"
#         detach: true
#         state: started

#     - name: Wait for the script to complete
#       community.docker.docker_container:
#         name: "your_container"
#         state: started
#       register: container_result
#       until: container_result.container.Status == 'exited'
#       retries: 30
#       delay: 10

#     - name: Copy result from Docker container
#       community.docker.docker_cp:
#         container_id: "your_container"
#         src: "/app/your_output_file.txt"
#         dest: "./yourrepository/your_output_file.txt"

#     - name: Remove Docker container
#       community.docker.docker_container:
#         name: "your_container"
#         state: absent

#     - name: Remove Docker image
#       community.docker.docker_image:
#         name: "your_image"
#         tag: "latest"
#         state: absent
